### ISSUE TITLE
Overriding bootstrap and some scss

### ISSUE THREAD

**Issue by minijus** [open-kudos/open-kudos-intern-web#120]
Just an example: https://github.com/open-kudos/open-kudos-intern-web/blob/aa813a18a3de400a1c04a8a9d46a9b8c739c2d9e/src/app/style.scss#L33-L41

First of all, I suppose you are using bootstrap as style framework. Thus, you could simply import only modules from bootstrap that you are using and edit/override the bootstrap config, but do not override specific classes directly.

Also, use SCSS, the code in link provided could look something like this for example:
```SCSS
.btn-danger {
  background: $color-pomegranate;
  border-color: $color-pomegranate;
  &:hover {
    background: $color-pomegranate-dark;
    border-color: $color-pomegranate-dark;
  }
}
```
